% Author: Jarod Hart
% Data: 11/15/17

% Description: This script uses Euler's method, Runge-Kutta order 2, and
% Runge-Kutta order 4 to find numerical solutions to a system of ODEs for a
% double pendulum.  The purpose is to compare the errors generated by the
% various solution techniques.

% Dependencies: Euler.m, RK2.m, RK4.m

% Resources:  A descrption of these equations can be found in physics
% textbooks or online.

addpath(genpath('../Numerical Solvers/'));

g=9.81; % force of gravity
L1=15; % length of first pendulum arm
L2=8; % length of second pendulum arm
m1=7; % mass of first point mass
m2=3; % mass of second point mass

theta1_0=0; % initial angle of first arm
theta2_0=0; % initial angle of second arm
omega1_0=1; % initial angular velocity of first arm
omega2_0=0; % initial angular velocity of second arm

a=0; % start of time interval
b=10; % end of time interval
N=100; % number of points for solver

M=m1+m2; % total mass
F=@(t,y)[y(3),...
         y(4),...
         (-g*(M+m1)*sin(y(1))-m2*sin(y(1)-2*y(2))-2*sin(y(1)-y(2))*m2...
              *(y(3)^2*L1*cos(y(1)-y(2))+y(4)^2*L2))...
              /(L1*(M+m1-m2*cos(2*y(1)-2*y(2)))),...
         (2*sin(y(1)-y(2))*(M*y(3)^2*L1+g*M*cos(y(1))+y(4)^2*L2*m2...
              *cos(y(1)-y(2))))/(L2*(M+m1-m2*cos(2*y(1)-2*y(2))))];
        % Function for the sysem of ODEs describing the double pendulum
        % (after reduction of order)

y0=[theta1_0,theta2_0,omega1_0,omega2_0]; % full initial condition

YEuler=Euler(a,b,N,y0,F); % solve using Euler
YRK2=RK2(a,b,N,y0,F); % solver using Runge-Kutta 2
YRK4=RK4(a,b,N,y0,F); % solver using Runge-Kutta 4

% parse the solution information
tEuler=YEuler(:,1)';
y1Euler=YEuler(:,2)';
y2Euler=YEuler(:,3)';
tRK2=YRK2(:,1);
y1RK2=YRK2(:,2);
y2RK2=YRK2(:,3);
tRK4=YRK4(:,1);
y1RK4=YRK4(:,2);
y2RK4=YRK4(:,3);

% make plots
figure
subplot(1,2,1)
hold on
plot(y1Euler,'r')
plot(y1RK2,'r-.')
plot(y1RK4,'r.')
title('First arm angle')
legend('Euler','Runge-Kutta 2','Runge-Kutta 4')
subplot(1,2,2)
hold on
plot(y2Euler,'b')
plot(y2RK2,'b-.')
plot(y2RK4,'b.')
title('Second arm angle')
legend('Euler','Runge-Kutta 2','Runge-Kutta 4')

figure
subplot(1,2,1)
plot(y1Euler,'ro-')
title('Euler: First arm angle')
subplot(1,2,2)
plot(y2Euler,'bo-')
title('Euler: Second arm angle')

figure
subplot(1,2,1)
plot(y1RK2,'rx-')
title('Runge-Kutta 2: First arm angle')
subplot(1,2,2)
plot(y2RK2,'bx-')
title('Runge-Kutta 2: Second arm angle')

figure
subplot(1,2,1)
plot(y1RK4,'r*-')
title('Runge-Kutta 4: First arm angle')
subplot(1,2,2)
plot(y2RK4,'b*-')
title('Runge-Kutta 4: Second arm angle')



